export declare const VISAGE: string;
export declare const SURFACE: string;
export declare const CONTAINER: string;
export declare const GRAPHIC: string;
export declare const TEXT: string;
export declare const SPRITE: string;
export declare const HEXAGON: string;
export declare const VIDEO: string;
export declare const LOOP: string;
